# Generated by Django 6.0 on 2025-12-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_source', models.CharField(choices=[('existing_site', 'Reuse from existing site'), ('client_provides', 'Client provides content'), ('de_writes', 'DE writes content')], default='client_provides', max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_build', 'In Build'), ('ready_for_review', 'Ready for Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('locked', 'Locked')], default='not_started', max_length=20)),
                ('preview_url', models.URLField(blank=True, help_text='Staging site preview URL')),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('best_practices', models.TextField(blank=True, help_text='Guidance for this page type')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
