# Generated by Django 6.0 on 2025-12-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='Local path or Drive file ID', max_length=500)),
                ('file_url', models.URLField(blank=True)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('storage_backend', models.CharField(default='local', max_length=20)),
                ('storage_ref', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('client', 'Client'), ('internal', 'Internal')], default='client', max_length=20)),
                ('kind', models.CharField(choices=[('client_task', 'Client Task'), ('internal_task', 'Internal Task'), ('page_review', 'Page Review'), ('info', 'Information')], default='client_task', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('why_it_matters', models.TextField(blank=True, help_text='Brief explanation of importance')),
                ('instructions', models.TextField(blank=True)),
                ('best_practices', models.TextField(blank=True, help_text='Collapsible guidance')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('submitted', 'Submitted'), ('needs_info', 'Needs More Info'), ('accepted', 'Accepted')], default='todo', max_length=20)),
                ('assigned_to_role', models.CharField(choices=[('client', 'Client'), ('designer', 'Designer')], default='client', max_length=20)),
                ('drive_folder_hint', models.CharField(blank=True, max_length=200)),
                ('phase', models.CharField(blank=True, help_text='Phase this card belongs to', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
