# Generated by Django 6.0 on 2025-12-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_type', models.CharField(choices=[('project_chat', 'Project Chat'), ('card_thread', 'Card Thread')], max_length=20)),
                ('triage_state', models.CharField(choices=[('needs_de', 'Needs DE Response'), ('waiting_client', 'Waiting on Client'), ('resolved', 'Resolved')], default='waiting_client', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
    ]
