# Generated by Django 6.0 on 2025-12-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('domain_registrar', 'Domain Registrar'), ('email_hosting', 'Email Hosting'), ('cms_admin', 'CMS Admin'), ('other', 'Other')], max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('encrypted_value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['credential_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phase', models.CharField(choices=[('discovery', 'Discovery'), ('creative', 'Creative'), ('launch', 'Launch'), ('complete', 'Complete')], default='discovery', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('complete', 'Complete'), ('archived', 'Archived')], default='active', max_length=20)),
                ('estimated_launch_date', models.DateField(blank=True, null=True)),
                ('actual_launch_date', models.DateField(blank=True, null=True)),
                ('sitemap_approved', models.BooleanField(default=False)),
                ('sitemap_approved_at', models.DateTimeField(blank=True, null=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=200)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('phase_order', models.JSONField(default=list)),
                ('discovery_cards', models.JSONField(default=list)),
                ('creative_cards', models.JSONField(default=list)),
                ('launch_cards', models.JSONField(default=list)),
                ('page_type_card_packs', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
